Category.create!(name: "Bird")
Category.create!(name: "Building")
Category.create!(name: "Cat")
Category.create!(name: "Dog")
Category.create!(name: "Food")
Category.create!(name: "People")
Category.create!(name: "Scenery")
