Category.create!(name: "Bird", icon_class: "flaticon-dove" )
Category.create!(name: "Building", icon_class: "flaticon-city")
Category.create!(name: "Cat", icon_class: "flaticon-black")
Category.create!(name: "Dog", icon_class: "flaticon-animals")
Category.create!(name: "Food", icon_class: "flaticon-drink")
Category.create!(name: "People", icon_class: "flaticon-users-group")
Category.create!(name: "Scenery", icon_class: "flaticon-mountain")
